name: period_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Data
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  get_it: ^9.2.0

  # Routing
  go_router: ^17.0.1

  # UI
  hugeicons: ^1.1.4
  table_calendar: ^3.2.0

  # Intl
  intl: ^0.20.2
  extensions_plus: ^1.6.0

  # Updates
  http: ^1.2.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
