name: periodility
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.1

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Core
  dartz: ^0.10.1
  equatable: ^2.0.8

  # Data
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.10.0
  get_it: ^9.2.0
  flutter_dotenv: ^6.0.0

  # Routing
  go_router: ^17.1.0

  # UI
  material_symbols_icons: ^4.2906.0
  skeletonizer: ^2.1.2
  pinput: ^6.0.2
  scaffold_navigation:
    path: dependencies/scaffold_navigation
  sliver_header_parallax:
    path: dependencies/sliver_header_parallax

  # Intl
  intl: ^0.20.2
  extensions_plus: ^1.6.0

  # Storage
  supabase_flutter: ^2.12.0
  shared_preferences: ^2.5.4
  isar_plus: ^1.2.2
  isar_plus_flutter_libs: ^1.2.2

  # Share
  share_plus: ^12.0.1

  # Notifications
  flutter_local_notifications: ^20.0.0

  # Utils
  path_provider: ^2.1.5
  uuid: ^4.5.2
  flutter_markdown_plus: ^1.0.7
  internet_connection_checker_plus: ^2.9.1+2
  talker_flutter: ^5.1.13
  talker_bloc_logger: ^5.1.13
  form_builder_validators: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Build runner
  build_runner: ^2.11.0

  # Generators
  freezed: ^3.2.5
  json_serializable: ^6.12.0

  # Analysis options
  very_good_analysis: ^10.1.0

  # Utils
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true

  assets:
    - dotenv
    - assets/icons/
    - assets/articles/
    - assets/articles/md/
