name: period_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.2

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Core
  dartz: ^0.10.1
  equatable: ^2.0.8

  # Data
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  get_it: ^9.2.0
  flutter_dotenv: ^6.0.0

  # Routing
  go_router: ^17.0.1

  # UI
  hugeicons: ^1.1.4
  skeletonizer: ^2.1.2
  pinput: ^6.0.1

  # Intl
  intl: ^0.20.2
  extensions_plus: ^1.6.0

  # Updates
  http: ^1.2.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.0

  # Storage
  shared_preferences: ^2.3.5
  supabase_flutter: ^2.12.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Share
  share_plus: ^12.0.1

  # Notifications
  flutter_local_notifications: ^19.0.0

  # Utils
  flutter_markdown_plus: ^1.0.7
  internet_connection_checker_plus: ^2.9.1+2
  talker_flutter: ^5.1.11
  form_builder_validators: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.4
  json_serializable: ^6.11.3
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - dotenv
    - assets/icons/